# Chess Opening Visualizer - GitHub Pages Configuration

# Site settings
title: Chess Opening Visualizer
description: Interactive chess opening trainer - Learn Italian Opening, Evans Gambit, and Scandinavian Defense
baseurl: ""
url: "https://yourusername.github.io"

# GitHub Pages settings
github_username: yourusername
repository: chess-opening-visualizer

# SEO and social
author: Mahmoud Elshenhab Using Claude
twitter_username: statswiz
github_username: shenhab

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Include files
include:
  - _pages

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Default settings
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
